**Imbalanced Dataset:**
A dataset with an unequal class distribution

In [24]:
import numpy as np
import pandas as pd

In [25]:
df = pd.read_csv('E:/ML/credit_data.csv')

In [26]:
df.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0.0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0
1,0.0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0
2,1.0,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0
3,1.0,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0
4,2.0,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0

In [27]:
df['Class'].value_counts()

Class
0    284315
1       492
Name: count, dtype: int64

This is Highly Imbalanced Dataset

In [28]:
legid = df[df.Class == 0]
fraud = df[df.Class == 1]

In [29]:
print(legid.shape)
print(fraud.shape)

(284315, 31)
(492, 31)

Build a sample dataset containing similar distribution of Legit & Fraudulent Transactionds

Number of Fraudulent Transactions --> 492

In [30]:
legid_sample = legid.sample(n=492)

In [31]:
print(legid_sample.shape)

(492, 31)

**Concatenate the Two DataFrames**

In [32]:
new_df = pd.concat([legid_sample,fraud], axis =0)

In [33]:
new_df.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
103942,68860.0,-1.734717,-0.527746,1.069533,-2.141518,-1.857342,-0.721295,-0.874520,0.808217,-2.539738,...,-0.122245,-0.498644,0.094342,0.346988,-0.359629,-0.568813,-0.183192,-0.152787,108.00,0
202635,134424.0,0.136785,1.016260,-1.062744,0.009192,0.163890,-1.326285,0.647392,0.150824,-0.088430,...,0.346732,0.923201,-0.000637,-0.102030,-0.289699,-0.145998,-0.080484,-0.046064,42.81,0
39727,39938.0,-0.996099,0.716801,1.686646,1.058163,0.578009,-0.351940,0.584137,-0.025660,-0.789450,...,0.109978,0.426810,-0.016261,0.091394,0.473612,-0.117532,0.000546,0.055775,2.76,0
222217,142878.0,0.159548,1.729489,-2.833998,-0.369472,1.776285,-1.122849,1.114891,0.176272,-0.856769,...,0.061337,0.336507,-0.156509,0.121045,-0.169746,0.537484,0.115903,0.042610,0.76,0
71985,54519.0,-0.329745,0.452744,2.318131,0.015103,-1.031207,-0.395686,-0.083731,0.026665,0.419612,...,-0.000404,0.173042,-0.026103,0.817735,-0.445471,1.015894,-0.110559,0.030482,18.39,0

In [34]:
new_df['Class'].value_counts()

Class
0    492
1    492
Name: count, dtype: int64